### ISSUE TITLE
Install fails after trying to update EE

### ISSUE THREAD

**Issue by xiano8494** [openspace42/raptor#2]
I get a message:
Now [re-]installing and updating EasyEngine...

Executing apt-get update, please wait...
[ Tue Apr  3 12:49:23 UTC 2018 ] You already have EasyEngine 3.7.5, exit status =  1
Downloading update script        Unable to download file, /tmp/eeupdate20180403-124924

And then the installer stops.

**Comment by nikksno** [comment]
I’ve been having the same issue during the last few days, I think it’s an EE issue but let me check it, will let you know within 24H.

**Comment by nikksno** [comment]
Yeah, it's an easyengine issue, since it's been happening every once in a while and updating ee isn't a major step i've allowed it to fail should it come to that. Also, I've integrated the installation of duplicity, mail_notifications, and easyengine itself to our underlying framework bash-functions, that also make installing EE more secure as it's not downloading a shell script over plain HTTP as instructed to do on their site [instead at least downloading from github over HTTPS]. I just pushed a beta, please try it out by removing the raptor dir, re-cloning, and installing with:

`bash raptor/setup -be`

Make sure to include the `-be` arguments to install the bleeding-edge version. Let me know if it works out for you. Thanks.

**Comment by xiano8494** [comment]
That's sorted it.
